version: '3.8'

services:
  redis:
    image: redis:7.4.0-alpine
    ports:
      - 6379:6379

  postgres:
    image: postgres:16.4
    environment:
      - POSTGRES_USER=morette
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - "./postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data: